# .shed.yml supporting automatic pushes.
owner: mvdbeek
name: tepid-discover
description: discovers TE variants from short-read sequencing
long_description: |
    TEPID uses illumina sequencing reads to identify novel TE variants. First,
    reads are mapped to a reference genome using bowtie2 and yaha. This produces
    two bam files, one containing mapped reads, and one containing mapped split
    reads. Python scripts are then used to identify the absence of reference TE
    insertions and the presence of non-reference insertions. Having a high-quality
    TE annotation and reference genome assembly, as well as deep sequencing
    coverage (>20x) and long reads (100 bp or more) will greatly improve the
    quality of TE presence/absence calls made.
categories:
  - Variant Analysis
homepage_url: https://github.com/ListerLab/TEPID
remote_repository_url: https://github.com/ListerLab/TEPID
